# Generated by Django 4.2.5 on 2023-09-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alma_Systems_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('indetification_code', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_person_mobile', models.CharField(blank=True, max_length=20)),
                ('clinic_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HP_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HP_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_serial_number', models.CharField(max_length=20)),
                ('hp_manufacturing_date', models.DateField()),
                ('size', models.FloatField()),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sansotechnical.hp_models')),
            ],
        ),
        migrations.CreateModel(
            name='Alma_Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_serial_number', models.CharField(max_length=20)),
                ('manufacturing_date', models.DateField()),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sansotechnical.alma_systems_models')),
            ],
        ),
    ]
