# Generated by Django 4.2.4 on 2023-09-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sansotechnical', '0003_givenitemsstatus_alter_alma_systems_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customershavehp',
            name='detachedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customershavehp',
            name='hp1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HP1', to='sansotechnical.hp_details'),
        ),
        migrations.AlterField(
            model_name='customershavehp',
            name='hp1GivenStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HP1_Given_Status', to='sansotechnical.givenitemsstatus'),
        ),
        migrations.AlterField(
            model_name='customershavehp',
            name='hp2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HP2', to='sansotechnical.hp_details'),
        ),
        migrations.AlterField(
            model_name='customershavehp',
            name='hp2GivenStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HP2_Given_Status', to='sansotechnical.givenitemsstatus'),
        ),
        migrations.AlterField(
            model_name='customershavehp',
            name='hp3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HP3', to='sansotechnical.hp_details'),
        ),
        migrations.AlterField(
            model_name='customershavehp',
            name='hp3GivenStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HP3_Given_Status', to='sansotechnical.givenitemsstatus'),
        ),
        migrations.AlterField(
            model_name='customershavehp',
            name='hp4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HP4', to='sansotechnical.hp_details'),
        ),
        migrations.AlterField(
            model_name='customershavehp',
            name='hp5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HP5', to='sansotechnical.hp_details'),
        ),
        migrations.AlterField(
            model_name='customershavehp',
            name='hp5GivenStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HP5_Given_Status', to='sansotechnical.givenitemsstatus'),
        ),
    ]
