# Generated by Django 4.2.4 on 2023-09-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sansotechnical', '0005_customershavehp_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customershavehp',
            name='hp4GivenStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HP4_Given_Status', to='sansotechnical.givenitemsstatus'),
        ),
    ]
