# Generated by Django 4.2.5 on 2023-09-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sansotechnical', '0006_alter_customershavehp_hp4givenstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='indetification_code',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='internal_id',
            field=models.IntegerField(unique=True),
        ),
    ]
