# Generated by Django 4.2.4 on 2023-09-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sansotechnical', '0007_alter_customers_indetification_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hp_models',
            old_name='model_name',
            new_name='model_name_HP',
        ),
    ]
