# Generated by Django 4.2.4 on 2023-10-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sansotechnical', '0008_rename_model_name_hp_models_model_name_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=30)),
            ],
        ),
    ]
